DET_SOURCE_DIR: '/aic/code/AICITY2022_Track1_TAG/datasets/detection/images/validation/S02/'
REID_MODEL: 'reid_model/resnext101_ibn_a_2.pth'
REID_BACKBONE: 'resnext101_ibn_a'
DET_IMG_DIR: '/aic/code/AICITY2022_Track1_TAG/datasets/validation/detect/'
DATA_DIR: '/aic/code/AICITY2022_Track1_TAG/datasets/validation/detect_reid2/'
REID_SIZE_TEST: [384, 384]
